### ISSUE TITLE
Add XML documentation for members designed for public consumption.

### ISSUE THREAD

**Issue by tacosontitan** [victoriaquasar/DotnetFetch#21]
## Summary

It is common practice to include XML documentation for publicly exposed members to help educate consumers on what things do, why they do them, and potential issues or side effects that can be encountered. There is also an added benefit in that most modern IDEs support some form of intellisense feature that utilizes XML documentation to give consumers real-time insight into your library.

## TL;DR

I propose that XML documentation be added for all members with an access modifier of:

- `public`
- `internal`
- `internal protected`
- `protected`

As a guideline, all members within the following files should be included as part of the PR that covers this issue:

- [x] Global Fetch
- [x] Models/FetchCorsException
- [x] Models/FetchInvalidCharsetException
- [x] Models/FetchOptions
- [x] Models/Response

**Comment by scarletquasar** [comment]
Solved in #22
