### ISSUE TITLE
Add support for VS Code.

### ISSUE THREAD

**Issue by tacosontitan** [victoriaquasar/DotnetFetch#27]
Some extensions in VS Code automatically create a `.vscode` folder and a `settings.json` file when working with a repository in VS Code (I'm looking at you C# Dev Kit). As a result, I recommend adding support for VS Code by:

- [ ] Create a `settings.json` file.
- [ ] Create a `tasks.json` file with a `build` and `publish` task.
- [ ] Create an `extensions.json` file to add the Microsoft C# extensions as recommended.

**Comment by tacosontitan** [comment]
I created this issue in hindsight of PR #25 to give the same searchable history provided by issue #26.

**Comment by scarletquasar** [comment]
Solved in #25
