### ISSUE TITLE
Move `DotnetFetch.Tests` to a `test` folder.

### ISSUE THREAD

**Issue by tacosontitan** [victoriaquasar/DotnetFetch#29]
If issues #26 and #27 are approved, then common practice is to move the test projects for the repository to a `test` for faster navigation and consistency with similar repositories.

- [x] Create a `test` directory.
- [x] Move `DotnetFetch.Tests` inside of `test`.
- [x] Update the `DotnetFetch.sln` file to use the correct path to the project.

**Comment by scarletquasar** [comment]
@tacosontitan please contact me in discord (@embersarlet) since I lost the contact with you
