### ISSUE TITLE
A test for the FetchInvalidMethodException exception must be created

### ISSUE THREAD

**Issue by sisco0** [victoriaquasar/DotnetFetch#5]
With the aim to provide wider coverage of the current test suite, the `FetchTests` class should be extended by creating a new `FetchInvalidMethodShouldThrowException` test case that ensures that an assertion of the type `FetchInvalidMethodException` is thrown when passing an invalid HTTP method to the `GlobalFetch.Fetch` function.

**Comment by scarletquasar** [comment]
Solved in #6
